url: "https://amoskiprotich-fermentation.github.io"
baseurl: "/World-Fermented-Foods"
title: World Fermented Foods
description: An open, curated database of traditional fermented foods.
header_pages:
  - index.md
  - foods.md
  - map.md
  - citation_policy.md

  
author: Amos Kiprotich

theme: minima

collections:
  foods:
    output: true
    permalink: /foods/:name/

defaults:
  - scope:
      path: ""
      type: foods
    values:
      layout: page
