url: "https://amoskiprotich-fermentation.github.io"
baseurl: "/World-Fermented-Foods"
title: World Fermented Foods
header_pages:
  - index.md
  - foods.md
description: >
  An open, curated global database of traditional fermented foods,
  their substrates, fermentation types, and associated microbiota.

author: Amos Kiprotich

theme: minima

collections:
  foods:
    output: true
    permalink: /foods/:name/

defaults:
  - scope:
      path: ""
      type: foods
    values:
      layout: page
